
name: 'learning_app_warehouse'
version: '1.0.0'

profile: 'learning_app_warehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  learning_app_warehouse:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view
    dl:
      +materialized: table
    dw:
      +materialized: table
    dm:
      +materialized: table

vars:
  future_timestamp: '9999-12-31 23:59:59'